version: '3'

services:
    scraper:
        build: ./app/
        volumes:
            - "app-volume:/tmp"
    
    webapp:
        build: ./webapp/
        expose:
            - 5000
        ports: 
            - "8888:5000"    
        volumes:
            - "app-volume:/tmp"
    
volumes:
    app-volume: 
    